### ISSUE TITLE
[Could be me] I tried setting this up and it's not working

### ISSUE THREAD

**Issue by HippHamster** [malaow3/AniTracker#1]
I followed your steps and it's not working. This is the output from the console after running the runner.sh:
```
TypeScript v4.1.3 Node.js v10.23.1 linux/amd64


Replit: Updating package configuration

--> npm ci
npm ERR! code ENOENT
npm ERR! syscall open
npm ERR! path /home/runner/anitracker/package.json
npm ERR! errno -2
npm ERR! enoent ENOENT: no such file or directory, open '/home/runner/anitracker/package.json'
npm ERR! enoent This is related to npm not being able to find a file.
npm ERR! enoent 

npm ERR! A complete log of this run can be found in:
npm ERR!     /home/runner/.npm/_logs/2022-05-30T20_15_47_726Z-debug.log
exit status 254


Replit: Package operation failed.
```
![image](https://user-images.githubusercontent.com/60238566/171054979-83d62da3-e364-4d4f-971c-843ba389a046.png)

**Comment by HippHamster** [comment]
`package.json: json: cannot unmarshal object into Go struct field packageJSON.dependencies of type string
`
Ok, changing the name to package.json. I get this.

**Comment by malaow3** [comment]
Hey there, I've made a pretty big renovation to this project -- you can find the info here: https://anilist.co/forum/thread/51920 . Unfortunately the setup is kinda complicated since there's no easy Crunchyroll API (I've since also migrated the tool to be Crunchyroll only following the Funimation - Crunchyroll merger) and I didn't feel comfortable managing other users logins (nor do I think they'd want me to). If you have any other questions feel free to reach out again in this thread or drop me a message on Anilist!

**Comment by HippHamster** [comment]
I wrote a comment on your thread about another issue I had with the new version.https://anilist.co/forum/thread/51920/1
